export const TRANSFORM_KEEP_KEY_METADATA = 'TRANSFORM_KEEP_KEY_METADATA';

export const AUTHORIZE_KEY_METADATA = 'AUTHORIZE_KEY_METADATA';

export const PERMISSION_KEY_METADATA = 'PERMISSION_KEY_METADATA';
